### ISSUE TITLE
Explain the inout int = 0 gotcha

### ISSUE THREAD

**Issue by TheGag96** [p0nce/d-idioms#131]
It looks like there was some sort of copy-paste error when writing up the `isVolcano` example. The enum inside `hasMagma` should also be `hasMagma`, not `hasDuration` -- I assume this came from some library where `hasDuration` existed. Just a quick fix.

Also, somewhat related, is the `(inout int = 0)` even necessary? Also, syntactically, what does that even do? Is it an anonymous function argument? I didn't even know such a thing was possible... I got it to work just fine without that.

**Comment by p0nce** [comment]
I don't know about `(inout int = 0)` I think it's something in Phobos that was debated not long ago. Not sure why it's useful but for the sake of the example yes we should remove it.

Thanks for the report, indeed I've made copy/paste errors.

**Comment by p0nce** [comment]
Fixed

**Comment by TheGag96** [comment]
Ah wait, it seems as though the inout parameter might matter. 

http://forum.dlang.org/post/mh68p8$2p56$1@digitalmars.com

It may not be still required, but there was a rule where you couldn't declare an inout variable unless there was an inout parameter in the function. Though I'm still not sure if that matters here...

EDIT: It is indeed still required. It's even still in std.range's source. Maybe a little comment explaining this trap?

**Comment by p0nce** [comment]
When I don't know why it's there, so indeed it deserves a paragraph
